/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VEIW;

/**
 *
 * @author Usuario
 */
public class telaENTRAR extends javax.swing.JFrame {

    /**
     * Creates new form telaENTRAR
     */
    public telaENTRAR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonprojeto = new javax.swing.JButton();
        jButtonartigo = new javax.swing.JButton();
        jButtontcc = new javax.swing.JButton();
        jButtoncoautor = new javax.swing.JButton();
        jButtonvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        jButtonprojeto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonprojeto.setText("Projeto");
        jButtonprojeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprojetoActionPerformed(evt);
            }
        });

        jButtonartigo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonartigo.setText("Artigo");
        jButtonartigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonartigoActionPerformed(evt);
            }
        });

        jButtontcc.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtontcc.setText("TCC");
        jButtontcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontccActionPerformed(evt);
            }
        });

        jButtoncoautor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtoncoautor.setText("Coautor");
        jButtoncoautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncoautorActionPerformed(evt);
            }
        });

        jButtonvoltar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonvoltar.setText("Voltar");
        jButtonvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonprojeto, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jButtonartigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtontcc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtoncoautor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButtonvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtontcc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonartigo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncoautor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonprojetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonprojetoActionPerformed
        // TODO add your handling code here:
        telaPROJETO objtelaprojeto = new telaPROJETO();
        objtelaprojeto.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButtonprojetoActionPerformed

    private void jButtontccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontccActionPerformed
        // TODO add your handling code here:
         telaTCC objtelatcc = new telaTCC();
        objtelatcc.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButtontccActionPerformed

    private void jButtonartigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonartigoActionPerformed
        // TODO add your handling code here:
         telaARTIGO objtelaartigo = new telaARTIGO();
        objtelaartigo.setVisible(true);
        
         dispose();
    }//GEN-LAST:event_jButtonartigoActionPerformed

    private void jButtoncoautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncoautorActionPerformed
        // TODO add your handling code here:
        telaCOAUTOR objtelacoautor = new telaCOAUTOR();
        objtelacoautor.setVisible(true);
        
         dispose();
    }//GEN-LAST:event_jButtoncoautorActionPerformed

    private void jButtonvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvoltarActionPerformed
        // TODO add your handling code here:
        telaPRINCIPAL objtelaprincipal = new telaPRINCIPAL();
        objtelaprincipal.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButtonvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaENTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaENTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaENTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaENTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaENTRAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonartigo;
    private javax.swing.JButton jButtoncoautor;
    private javax.swing.JButton jButtonprojeto;
    private javax.swing.JButton jButtontcc;
    private javax.swing.JButton jButtonvoltar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
