/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VEIW;

import DTO.UsuarioDTO;
import connection.usuario;
import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class telaPRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form telaPRINCIPAL
     */
    public telaPRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelprincipal = new javax.swing.JPanel();
        jPanelcadastrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextcadastraremail = new javax.swing.JTextField();
        jPasswordconfirmarsenha = new javax.swing.JPasswordField();
        jPasswordcadastrarsenha = new javax.swing.JPasswordField();
        jButtoncadastrar = new javax.swing.JButton();
        jPanellogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordloginsenha = new javax.swing.JPasswordField();
        jTextNome1 = new javax.swing.JTextField();
        jButtonentrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckcadastro = new javax.swing.JCheckBoxMenuItem();
        jChecklogin = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelprincipal.setLayout(new java.awt.CardLayout());

        jPanelcadastrar.setBackground(new java.awt.Color(0, 102, 102));
        jPanelcadastrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setText("Cadastrar Responsável");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setText("Cadastrar senha");

        jPasswordconfirmarsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordconfirmarsenhaActionPerformed(evt);
            }
        });

        jButtoncadastrar.setText("Cadastrar");

        javax.swing.GroupLayout jPanelcadastrarLayout = new javax.swing.GroupLayout(jPanelcadastrar);
        jPanelcadastrar.setLayout(jPanelcadastrarLayout);
        jPanelcadastrarLayout.setHorizontalGroup(
            jPanelcadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcadastrarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelcadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelcadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPasswordcadastrarsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                        .addComponent(jPasswordconfirmarsenha)
                        .addComponent(jLabel1)
                        .addComponent(jTextcadastraremail)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtoncadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelcadastrarLayout.setVerticalGroup(
            jPanelcadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcadastrarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextcadastraremail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPasswordcadastrarsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordconfirmarsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtoncadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jPanelprincipal.add(jPanelcadastrar, "tela1");

        jPanellogin.setBackground(new java.awt.Color(0, 102, 102));
        jPanellogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Usuario do Responsável");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("Senha do Responsável");

        jButtonentrar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonentrar.setText("Entrar");
        jButtonentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonentrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelloginLayout = new javax.swing.GroupLayout(jPanellogin);
        jPanellogin.setLayout(jPanelloginLayout);
        jPanelloginLayout.setHorizontalGroup(
            jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelloginLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPasswordloginsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelloginLayout.setVerticalGroup(
            jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelloginLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordloginsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelprincipal.add(jPanellogin, "tela2");

        jMenu1.setText("Opções");

        jCheckcadastro.setSelected(true);
        jCheckcadastro.setText("Cadastro");
        jCheckcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckcadastroActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckcadastro);

        jChecklogin.setSelected(true);
        jChecklogin.setText("Login");
        jChecklogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckloginActionPerformed(evt);
            }
        });
        jMenu1.add(jChecklogin);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckloginActionPerformed
        // TODO add your handling code here:
                 CardLayout cl = (CardLayout) jPanelprincipal.getLayout();
        cl.show(jPanelprincipal, "tela2");
    }//GEN-LAST:event_jCheckloginActionPerformed

    private void jPasswordconfirmarsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordconfirmarsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordconfirmarsenhaActionPerformed

    private void jButtonentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonentrarActionPerformed
       Logar();
        
    }//GEN-LAST:event_jButtonentrarActionPerformed

    private void jCheckcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckcadastroActionPerformed
        // TODO add your handling code here:
          CardLayout cl = (CardLayout) jPanelprincipal.getLayout();
        cl.show(jPanelprincipal, "tela1");
                
    }//GEN-LAST:event_jCheckcadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void Logar() {
             try {
            
             String nome_usuario, senha_usuario;
        
        nome_usuario = jTextNome1.getText();
        senha_usuario = jPasswordloginsenha.getText();
        
        UsuarioDTO objusuariodto = new UsuarioDTO();
        objusuariodto.setNome_usuario(nome_usuario);
        objusuariodto.setSenha_usuario(senha_usuario);
        
         usuario objusuariodao = new usuario();
            ResultSet rsusuario = objusuariodao.autenticacaoUsuario(objusuariodto);
            
            if (rsusuario.next()) {
                // Chamar tela que quero abrir
                telaENTRAR objtelaentrar = new telaENTRAR();
                objtelaentrar.setVisible(true);
                
                dispose();
                
            }else{
                // Enviar mensagem dizendo incorreto
                JOptionPane.showMessageDialog(null, "Usuário ou Senha incorreto");
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "TelaPRINCIPAL" + erro);
        }
    }                                           
    
           
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncadastrar;
    private javax.swing.JButton jButtonentrar;
    private javax.swing.JCheckBoxMenuItem jCheckcadastro;
    private javax.swing.JCheckBoxMenuItem jChecklogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelcadastrar;
    private javax.swing.JPanel jPanellogin;
    private javax.swing.JPanel jPanelprincipal;
    private javax.swing.JPasswordField jPasswordcadastrarsenha;
    private javax.swing.JPasswordField jPasswordconfirmarsenha;
    private javax.swing.JPasswordField jPasswordloginsenha;
    private javax.swing.JTextField jTextNome1;
    private javax.swing.JTextField jTextcadastraremail;
    // End of variables declaration//GEN-END:variables
}
